Fix to ArbitratedScratchpad.h when Numbanks is not a power of 2
NVlabs/matchlib pull request #8
Opened 2022-05-13 15:09 UTC by ttambe

Pull request addressing issue #6 when `NumBanks` is not a power of 2. 

However the problem with this fix is that the divider will still be instantiated even if NumBanks is a power of 2 (although the divider won't be used).  In order to do conditional compile-time inclusion (or exclusion) of code using the `NumBanks` template parameter, it seems like we'll need C++17 in order to use the `constexpr if` statement for this purpose. Lots of things in MatchLib will break as a result when C++17 is activated.  

Still sharing the solution even though it might be hard to merge it.

2022-05-16 19:03 UTC, ben-k requested changes

2022-05-16 19:03 UTC, ben-k commented on cmod/include/ArbitratedScratchpad.h
> +      else {
```suggestion
      if (NumInputs == 1) {
        bank_sel[in_chan] = 0;
      } else {
```

2022-05-16 19:03 UTC, ben-k commented on cmod/include/ArbitratedScratchpad.h
> +      else {
```suggestion
      if (NumInputs == 1) {
        bank_req[in_chan].addr = curr_cli_req.addr[in_chan];
      } else {
```

2022-05-16 19:03 UTC, ben-k commented on cmod/include/ArbitratedScratchpad.h
> +  bool is_nbanks_power_of_2 = (NumBanks & (NumBanks - 1)) == 0;
```suggestion
  static const bool is_nbanks_power_of_2 = (NumBanks & (NumBanks - 1)) == 0;
```

2022-05-16 19:03 UTC, ben-k commented on cmod/include/ArbitratedScratchpad.h
> +  //Check if NumBanks is a power of 2
Can remove these

2022-05-16 19:06 UTC, ben-k commented
Hey Thierry - we think this proposal is mostly OK as-is, because Catapult's constant propagation will remove the unused branch for any specific hardware instantiation.  (The C++ compiler may not, but that doesn't really matter here.)

If you can address the suggestions in the review, and then rebase against main, I'll run this on our CI in preparation for merge.

2022-05-17 01:33 UTC, ttambe commented
Hi Ben, it's good to know that Catapult's constant propagation will remove unused branches. I think all the suggestions have been addressed and rebased w/ main.

2022-05-25 00:46 UTC, ben-k commented
Thanks Thierry.  The only other thing we spotted is that we would define the bank address width a bit more carefully, as it does not need the "+1" in the original power-of-two case.  Something like this:

```
static const int bank_addr_width = (is_nbanks_power_of_2 && (NumBanks > 1)) ? (addr_width - log2_nbanks) : (addr_width - log2_nbanks + 1);
typedef NVUINTW(bank_addr_width) bank_addr_t;   // address within bank
```

Let me know if that looks good to you and I will clean everything up locally and merge it in.

2022-05-25 00:55 UTC, ttambe commented
Hi Ben, yes this change looks good. Thanks for merging this solution!

-Thierry

2022-05-25 18:26 UTC, ben-k commented
Ok, this is merged with d7cb25d.

2022-05-25 18:26 UTC, closed without merging